### ISSUE TITLE
Do you support Pytorch?

### ISSUE THREAD

**Issue by G-Bong** [jerryuhoo/Masked-Face-Recognition#2]
Hello

First of all, thank you so much for your great work.

I have a question that do you have a plan for changing whole code to Pytorch?

**Comment by jerryuhoo** [comment]
Hi, GyeongBong Kim

Sorry, this project doesn't support Pytorch. This is just a course project I did when I was in the university. And I am not going to update further because recently I have been busy with other works. Thank you for your understanding!

Yifeng

**Comment by G-Bong** [comment]
@jerryuhoo I understand. Thank you so much.
I need to change your whole code into Pytorch for my needs.
When I finish it, I would share the cod with you.

Have a niceday

GBKim
