### ISSUE TITLE
i got this problem *** Can't open "face_detector/deploy.prototxt" ***

### ISSUE THREAD

**Issue by Kachasukintim** [jerryuhoo/Masked-Face-Recognition#3]
C:\Users\Mario\Desktop\Masked-Face-Recognition-master> python facenet/contributed/real_time_face_recognition.py
2021-11-15 15:52:21.103666: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2021-11-15 15:52:21.103765: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From C:\Users\Mario\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\compat\v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be rem
oved in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "facenet/contributed/real_time_face_recognition.py", line 33, in <module>
    import face_mask as face
  File "C:\Users\Mario\Desktop\Masked-Face-Recognition-master\facenet\contributed\face_mask.py", line 56, in <module>
    faceNet = cv2.dnn.readNet(PROTOTXT_PATH, CAFFE_PATH)
cv2.error: OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1126: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "face_detector/deploy.prototxt" in function 'cv::dnn::ReadP
rotoFromTextFile'

pls help me

**Comment by jerryuhoo** [comment]
Maybe you should run the command ```python real_time_face_recognition.py``` in the path that is the same as real_time_face_recognition.py. 
https://github.com/jerryuhoo/Masked-Face-Recognition/blob/de8b70fc7e20e252acc6ed5f082fab83c15c115e/facenet/contributed/face_mask.py#L52
This is a relative path, or you can also change it to an absolute path.

**Comment by Kachasukintim** [comment]
I don't understand, I tried cd facenet/contributed then run the command python real_time_face_recognition.py I got the same problem How can I run it?

**Comment by jerryuhoo** [comment]
> I don't understand, I tried cd facenet/contributed then run the command python real_time_face_recognition.py I got the same problem How can I run it?

That's weird, I think "Can't open "face_detector/deploy.prototxt" is because it cannot find the deploy.prototxt file, either the file is missing or the path is incorrect.

**Comment by Kachasukintim** [comment]
I can solve the problem. I moved the deploy.prototxt and res10_300x300_ssd_iter_140000.caffemodel files. and edited the path part of face_mask.py it works thanks for the help
